server:
  port: 80
  servlet:
    context-path: /csky

spring:
  datasource:
    druid:
      url: jdbc:mysql://47.100.249.168:3306/csky?useSSL=false&serverTimezone=UTC
      username: root
      password: qlwILj]MXp^sKi3GBy1Wr
      driver-class-name: com.mysql.cj.jdbc.Driver
