spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      # 如果后端项目服务器和数据库服务器不在同一台主机，则需要修改localhost为数据库服务器ip地址
      #      url: jdbc:mysql://localhost/test?characterEncoding=utf8
      url: jdbc:mysql://47.100.249.168/csky?characterEncoding=utf8
      username: root
      password: qlwILj]MXp^sKi3GBy1Wr

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: shu.java.csky.entity

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
